name: drkiesel
favicon: null
layout_spectrum: 0.33279
typography_spectrum: 0.13402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee9b01'
    - '#636363'
    - '#96cd18'
    - '#f8ce87'
  brandStrength: 0.4742823946289718
  lightness: 0.4213083595968783
  saturation: 0.4588124973233789
  rhythmicContrast: 0.75
purpose: []
